<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- back Caster Wheel Link -->
    <link name="bcaster_wheel_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${bcaster_wheel_radius}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${bcaster_wheel_radius}"/>
            </geometry>
        </collision>

        <xacro:inertial_sphere mass="${bcaster_wheel_mass}" radius="${bcaster_wheel_radius}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_sphere>
    </link>

    <!-- Caster Wheel Joit -->
    <joint name="bcaster_wheel_joint" type="fixed">
        <origin xyz="${bcaster_wheel_offset_x} 0.0 ${bcaster_wheel_offset_z}" rpy="0.0 0.0 0.0"/>
        <parent link="chassis_link"/>
        <child link="bcaster_wheel_link"/>
    </joint>


    <!-- Caster Holder (Only for visuals) -->
    <link name="bcaster_holder">
        <visual>
            <geometry>
                <cylinder radius="${bcaster_wheel_radius/2}" length="${bcaster_wheel_offset_z*2}"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>
    <joint name="bholder_joint" type="fixed">
        <origin xyz="${bcaster_wheel_offset_x} 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="chassis_link"/>
        <child link="bcaster_holder"/>
    </joint>

    <gazebo reference="bcaster_wheel_link">
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>



</robot>